### ISSUE TITLE
[Question] front usb and bluetooth not work

### ISSUE THREAD

**Issue by Tert-butyllithium** [Hackintoshlifeit/GA-Z490M-Gaming-X#4]
CPU: QTB1  (10900es)
MB: GA Z490M GAMING X
GPU: UHD 630
OS Version: 11.3.1

Thanks for your sharing, but I have just found bluetooth and front usb not work. 
I was curious because I thought the same motherboard should have the same usb mapping.

After hours of pointless attempts, finally, I tried `usbinjectall.kext` and then all went well...(but it seems not to be recommended)

**Comment by Baio1977** [comment]
The real problem is the Apple limit of N 15 ports, from OS 11.3 the port limit patch that extended the N of ports to 26 has been removed, so in the EFI you find MY port mapping and if you use the 30 PIN connector on the MOBO you need to redo the port mapping

This my Map USB Port if you use the 30 pin connector with 2 USB you also need the HS07 HS08 SS07 SS08 ports
![Schermata 2021-06-10 alle 18 27 48](https://user-images.githubusercontent.com/59058746/121562269-948a0b00-ca19-11eb-9d08-b2afd744ea82.png)

**Comment by plutosherry** [comment]
The number of USB ports exceeds 15. Can you add the excess part without deleting it?
